# Generated by Django 4.0.7 on 2022-08-10 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='Movie title')),
                ('description', models.TextField(blank=True, verbose_name='Movie description')),
                ('poster', models.ImageField(blank=True, upload_to='posters/', verbose_name='Link to get poster')),
                ('kinopoisk_url', models.URLField(max_length=255, verbose_name='Link to kinopoisk page')),
                ('duration', models.DurationField(help_text='Input in minutes or use format DD:hh:mm', verbose_name='Movie length')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
            },
        ),
        migrations.CreateModel(
            name='UserMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('is_watched', models.BooleanField(default=False, verbose_name='Movie watching status')),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='Likes by friends')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='movies.movie', verbose_name='Added movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to=settings.AUTH_USER_MODEL, verbose_name='User who add movie')),
            ],
            options={
                'verbose_name': 'UserMovie',
                'verbose_name_plural': 'UsersMovies',
            },
        ),
        migrations.AddConstraint(
            model_name='usermovie',
            constraint=models.UniqueConstraint(fields=('user', 'movie'), name='movies_usermovie_unique'),
        ),
    ]
