# Generated by Django 4.0.7 on 2022-08-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='kinopoisk_url',
        ),
        migrations.AddField(
            model_name='movie',
            name='kinopoisk_id',
            field=models.PositiveIntegerField(default=0, unique=True, verbose_name='Movie ID on kinopoisk'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Movie description'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.DurationField(help_text='Input in minutes or use format DD:hh:mm', null=True, verbose_name='Movie length'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='Link to get poster'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Movie title'),
        ),
    ]
