# Generated by Django 4.0.7 on 2022-08-19 07:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_friendship_user_friends_friendship_friend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['uid'], name='uid_idx'),
        ),
    ]
